language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - rvm install 2.3.1
  - rvm use 2.3.1
  - gem install bundler
  - bundle install
script:
  - nosetests
  - bundle exec danger
